config/routes.rb
Rails.application.routes.draw do
  get 'tasks/index'
  get 'tasks/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # Read all my tasks
  get "/tasks", to: "tasks#index", as: :tasks

  # Create a task in 2 steps: 1 action for form / 1 action to create the instance
  # one page just for the form itself
  get "/tasks/new", to: "tasks#new", as: :new_task
  # this action is just to create the instance ()
  post "/tasks", to: "tasks#create"

  # one page just for the form itself
  get "/tasks/:id/edit", to: "tasks#edit", as: :update_task
  # this action is just to update the instance
  patch "/tasks/:id", to: "tasks#update", as: :task # why is as: :task above the other routes below?

  # delete a task
  delete "/tasks/:id", to: "tasks#destroy"


  # Read one of my tasks
  # /tasks/1
  get "/tasks/:id", to: "tasks#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  # associations
  # validations
  # validates :column_name, whatever_validation
  validates :title, presence: true
  validates :details, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # "/tasks"
  def index
    @tasks = Task.all
  end

  # "/tasks/1"
  def show
    @task = Task.find(params[:id])
    @complete = @task[:completed]

    if @complete
      @completed = "✅ Task is complete!"
    else
      @completed = "❌ Task is Not complete!"
    end
  end

  # "/tasks/new"
  def new
    @task = Task.new
  end

  # to get to this action, I have to submit a form -> post /restaurants
  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to task_path(@task)
    else
      render "new", status: :unprocessable_entity
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: task do |f| %>
<%= f.label :title %>
<%= f.text_field :title, class: "form-control"%>
<%= f.label :details %>
<%= f.text_field :details, class: "form-control" %>
<%= f.label :completed, "Completed" %>
<%= f.check_box :completed %>
<%= f.submit "Submit", class: "btn btn-primary mt-3" %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container mt-3">
  <h1>Edit Task</h1>
  <%= render "tasks/form", task: @task %>
</div>

app/views/tasks/index.html.erb
<div class="container">
<h1 class="mt-3 text-decoration-underline">Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <%= link_to task_path(task), class: "list-unstyled text-decoration-none" do %>
    <li><%= task[:title].capitalize %></li>
    <% end %>
  <% end %>
</ul>

<%= link_to "Create new task", new_task_path, class: "btn btn-success" %>
</div>

app/views/tasks/new.html.erb
<div class="container mt-3">
  <h1>Create New Task</h1>
  <%= render "tasks/form", task: @task %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h1 class="mt-3 text-decoration-underline"><%= @task[:title].capitalize %></h1>
  <h2 class="mt-3 text-secondary">Details</h2>
  <p class="mt-2"><%= @task[:details] %></p>
  <p><%= @completed %></p>
  <%= link_to "Back to list", tasks_path, class: "btn btn-secondary" %>
  <%= link_to "Edit Task", update_task_path, class: "btn btn-primary" %>
  <%= link_to "Delete", task_path(@task), data: { turbo_method: :delete, turbo_confirm: "Delete #{@task.title}?" }, class: "btn btn-danger" %>
</div>